// modules/prompt-builder.js
// Structured Prompt Builder module.
//
// Flow: user picks a visual style (dropdown), enters brand + product info,
// then per product hits "Enhance" on the Description field and/or the
// Visual Details field. Each Enhance call sends that field's current text
// plus full context (style, brand, category, product) to an NVIDIA text
// model and gets back a rewritten version of just that field.
//
// AI is used ONLY for that per-field enhancement (sharpening wording,
// adding sensory/visual detail). The final, full video-generation prompt
// (Step 4) is never generated by an AI model — it is assembled from a
// fixed template per visual style (see STYLE_TEMPLATES below), slotting in
// the brand info and each product's (already-enhanced-if-the-user-chose-to)
// description / visual details text verbatim. This keeps the final output
// deterministic, free, and instant.
//
// Uses the hub's shared NVIDIA free-tier key mechanism (see
// TEMPORARY_KEY_MODULES / TEMP_NVIDIA_API_KEY in routes/modules.js) —
// same as chatbot / message-writer / social-content — for the per-field
// Enhance calls only.

const NvidiaProvider = require('../providers/nvidia');
const pool = require('../db');

// Visual styles offered in the dropdown. Used both to populate the UI and
// to steer the AI enhancement toward a consistent look across a catalog.
const STYLE_OPTIONS = [
  { id: 'realistic', name: 'Realistic', icon: '📷', description: 'Hyper-realistic, photographic lighting and true-to-life textures.' },
  { id: '3d', name: '3D Render', icon: '🧊', description: 'Polished 3D CGI render with studio-quality product lighting.' },
  { id: '2d', name: '2D Flat', icon: '🔷', description: 'Clean flat 2D illustration with bold vector shapes and color.' },
  { id: 'cartoon', name: 'Cartoon', icon: '🎨', description: 'Playful animated cartoon style with a vibrant palette.' },
  { id: 'hologram', name: 'Holographic', icon: '💠', description: 'Futuristic holographic projection with neon-chromatic glow.' },
  { id: 'pixar', name: 'Pixar-style 3D', icon: '🎬', description: 'Warm, storybook 3D animation with soft global illumination.' },
  { id: 'popup-book', name: 'Pop-up Book', icon: '📖', description: 'Whimsical layered paper pop-up-book diorama look.' },
  { id: 'motion-graphics', name: 'Motion Graphics', icon: '⚡', description: 'Bold modern motion-graphics style with kinetic shapes.' },
];

const STYLE_MAP = Object.fromEntries(STYLE_OPTIONS.map(s => [s.id, s]));

// ──────────────────────────────────────────────
// Preset template library for the final, full prompt (Step 4).
//
// One template per visual style. No AI is involved in filling these in —
// it's plain string substitution using the brand/product fields the user
// (optionally, AI-)enhanced earlier. Placeholders:
//   {brand}    {tagline}    {category}    {style}
//   {productName}  {price}  {description}  {visualDetails}
// ──────────────────────────────────────────────
const STYLE_TEMPLATES = {
  realistic: {
    opening: 'Hyper-realistic, photographic AI video opening for {brand}{taglineSuffix}. Natural studio lighting, true-to-life textures, shallow depth of field, cinematic camera move establishing the {category} brand identity.',
    product: 'Realistic close-up product shot of {productName}{priceSuffix}. {description} {visualDetails} Photographic lighting, true-to-life materials and textures, smooth camera glide around the product.',
    closing: 'Closing shot: {brand} logo on a clean, realistic set, soft studio lighting fading to the brand mark{taglineClosing}.',
  },
  '3d': {
    opening: 'Polished 3D CGI render opening for {brand}{taglineSuffix}. Studio-quality product lighting, clean gradient backdrop, smooth camera orbit introducing the {category} collection.',
    product: '3D rendered hero shot of {productName}{priceSuffix}. {description} {visualDetails} Studio-quality lighting, glossy CGI materials, slow 360-degree turntable rotation.',
    closing: 'Closing 3D render: {brand} logo materializes with soft reflections and studio lighting{taglineClosing}.',
  },
  '2d': {
    opening: 'Clean flat 2D illustrated opening for {brand}{taglineSuffix}. Bold vector shapes, flat color palette, simple geometric animation introducing the {category} line.',
    product: 'Flat 2D vector illustration of {productName}{priceSuffix}. {description} {visualDetails} Bold shapes, flat colors, clean vector line work with simple slide/scale transitions.',
    closing: 'Closing flat 2D frame: {brand} logo on a bold color block, minimal vector shapes{taglineClosing}.',
  },
  cartoon: {
    opening: 'Playful animated cartoon opening for {brand}{taglineSuffix}. Vibrant color palette, bouncy motion, whimsical character energy introducing the {category} products.',
    product: 'Cartoon-style animated shot of {productName}{priceSuffix}. {description} {visualDetails} Vibrant colors, exaggerated bouncy motion, playful cartoon shading.',
    closing: 'Closing cartoon frame: {brand} logo bounces in with a vibrant, playful flourish{taglineClosing}.',
  },
  hologram: {
    opening: 'Futuristic holographic projection opening for {brand}{taglineSuffix}. Neon-chromatic glow, floating scan-line particles, sci-fi camera sweep introducing the {category} range.',
    product: 'Holographic projection of {productName}{priceSuffix}. {description} {visualDetails} Neon-chromatic glow, flickering scan lines, particles orbiting the projected product.',
    closing: 'Closing hologram: {brand} logo flickers into a neon-chromatic holographic projection{taglineClosing}.',
  },
  pixar: {
    opening: 'Warm, storybook 3D animation opening for {brand}{taglineSuffix}. Soft global illumination, gentle camera push, inviting animated intro to the {category} world.',
    product: 'Pixar-style animated hero shot of {productName}{priceSuffix}. {description} {visualDetails} Soft global illumination, warm storybook color grading, gentle character-like camera motion.',
    closing: 'Closing storybook frame: {brand} logo glows warmly under soft global illumination{taglineClosing}.',
  },
  'popup-book': {
    opening: 'Whimsical layered paper pop-up-book opening for {brand}{taglineSuffix}. Hand-crafted paper textures, layered diorama depth, gentle unfolding motion introducing the {category} story.',
    product: 'Pop-up-book diorama shot of {productName}{priceSuffix}. {description} {visualDetails} Layered paper-craft textures, soft diorama lighting, gentle paper-fold reveal animation.',
    closing: 'Closing pop-up page: {brand} logo unfolds from layered paper craft{taglineClosing}.',
  },
  'motion-graphics': {
    opening: 'Bold modern motion-graphics opening for {brand}{taglineSuffix}. Kinetic geometric shapes, sharp color blocks, energetic typographic motion introducing the {category} lineup.',
    product: 'Motion-graphics product showcase of {productName}{priceSuffix}. {description} {visualDetails} Kinetic shapes, bold color blocks, sharp graphic transitions around the product.',
    closing: 'Closing motion-graphics frame: {brand} logo snaps into place with a kinetic geometric flourish{taglineClosing}.',
  },
};

const DEFAULT_TEMPLATE = STYLE_TEMPLATES.realistic;

// Fill a template string with brand/product context. Pure string
// substitution — no AI call.
function fillTemplate(template, ctx) {
  return template
    .replace(/{brand}/g, ctx.brand || 'the brand')
    .replace(/{category}/g, ctx.category || 'product')
    .replace(/{style}/g, ctx.style || '')
    .replace(/{productName}/g, ctx.productName || 'the product')
    .replace(/{priceSuffix}/g, ctx.price ? `, priced at ${ctx.price}` : '')
    .replace(/{description}/g, ctx.description || '')
    .replace(/{visualDetails}/g, ctx.visualDetails || '')
    .replace(/{taglineSuffix}/g, ctx.tagline ? `, "${ctx.tagline}"` : '')
    .replace(/{taglineClosing}/g, ctx.tagline ? `, tagline "${ctx.tagline}"` : '')
    .replace(/\s+/g, ' ')
    .trim();
}

const NVIDIA_MODELS = [
  'meta/llama-3.1-70b-instruct',
  'meta/llama-3.1-8b-instruct',
];
const DEFAULT_MODEL = 'meta/llama-3.1-70b-instruct';

const FIELD_LABELS = {
  description: 'product description',
  visualDetails: 'visual / on-screen scene details for an AI video generator',
};

// List available styles (for GET /api/modules/prompt-builder/styles)
function listStyles() {
  return STYLE_OPTIONS;
}

// Get model catalog (for future model selection UI)
function getModelCatalog() {
  return NVIDIA_MODELS.map(model => ({
    id: model,
    name: model.replace('meta/', 'Meta ').replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
    description: model.includes('70b') ? 'Most capable model for complex prompts' : 'Fast, efficient model for quick iterations',
  }));
}

// Generate full prompt for all products at once (Step 4).
//
// NOT an AI call. AI is used only in enhanceField() to sharpen a single
// product's description/visual-details text. This step just stitches the
// brand info + each product's (possibly already-enhanced) text into the
// fixed template for the chosen visual style — same style dropdown used
// throughout the builder, so the "preset library" is STYLE_TEMPLATES above.
function generateFullPrompt(requestBody) {
  const {
    brandName = '',
    category = '',
    tagline = '',
    styleId = '',
    styleName = '',
    products = [],
  } = requestBody;

  if (!brandName || !brandName.trim()) {
    throw new Error('Brand name is required');
  }
  if (!products.length) {
    throw new Error('At least one product is required');
  }

  const style = STYLE_MAP[styleId] || null;
  const template = STYLE_TEMPLATES[styleId] || DEFAULT_TEMPLATE;
  const displayStyleName = style?.name || styleName || 'Custom';

  const baseCtx = {
    brand: brandName.trim(),
    category: category.trim(),
    tagline: tagline.trim(),
    style: displayStyleName,
  };

  const scenes = [];

  scenes.push({
    title: 'Opening Brand Shot',
    description: fillTemplate(template.opening, baseCtx),
  });

  products.forEach((p, i) => {
    const ctx = {
      ...baseCtx,
      productName: (p.name || `Product ${i + 1}`).trim(),
      price: (p.price || '').trim(),
      description: (p.description || '').trim(),
      visualDetails: (p.visualDetails || '').trim(),
    };
    scenes.push({
      title: p.name ? `${p.name} Showcase` : `Product ${i + 1} Showcase`,
      description: fillTemplate(template.product, ctx),
    });
  });

  scenes.push({
    title: 'Closing Call-to-Action',
    description: fillTemplate(template.closing, baseCtx),
  });

  const finalPrompt = scenes.map(s => s.description).join('\n\n');

  return {
    prompt: finalPrompt,
    scenes,
    model: null, // template-based — no AI model involved
    usage: null,
  };
}

// POST /api/modules/prompt-builder  (dispatched from routes/modules.js)
// body: {
//   field: 'description' | 'visualDetails',
//   text: string,               // current field content the user typed
//   styleId: string,            // one of STYLE_OPTIONS ids, applies catalog-wide
//   brandName, category, tagline,
//   productName, price,         // context for this specific product
//   model                       // optional override
// }
async function enhanceField(requestBody, apiKeys, userId) {
  const {
    action = 'enhance_field',
    field,
    text = '',
    styleId,
    brandName = '',
    category = '',
    tagline = '',
    productName = '',
    price = '',
    products = [],
    model: requestedModel,
  } = requestBody;

  // Handle generate_full_prompt action — template-based, no AI/API key needed.
  if (action === 'generate_full_prompt') {
    return generateFullPrompt(requestBody);
  }

  // Handle rewrite_prompt action — "Rewrite Prompt" mode. Unlike
  // generate_full_prompt, this DOES call the AI model (see rewritePrompt
  // below), so it goes through the normal NVIDIA key / temp-key gate in
  // routes/modules.js like enhance_field does.
  if (action === 'rewrite_prompt') {
    return rewritePrompt(requestBody, apiKeys);
  }

  // Original enhance_field behavior
  if (!field || !FIELD_LABELS[field]) {
    throw new Error('field must be "description" or "visualDetails"');
  }
  if (!text || !text.trim()) {
    throw new Error(`Enter some ${FIELD_LABELS[field]} text before enhancing it`);
  }
  if (!apiKeys.nvidia?.api_key) {
    throw new Error('NVIDIA API key not configured. Add it in Profile > API Keys.');
  }

  const style = STYLE_MAP[styleId] || null;
  const model = NVIDIA_MODELS.includes(requestedModel) ? requestedModel : DEFAULT_MODEL;

  const contextLines = [
    brandName && `Brand: ${brandName}`,
    category && `Category: ${category}`,
    tagline && `Tagline: ${tagline}`,
    productName && `Product: ${productName}`,
    price && `Price: ${price}`,
    style && `Visual style for the whole catalog: ${style.name} — ${style.description}`,
  ].filter(Boolean).join('\n');

  const systemPrompt = `You are an expert copywriter for AI video/image generation prompts.
You will be given a ${FIELD_LABELS[field]} that the user already wrote, plus context about the brand, product, and chosen visual style.
Rewrite ONLY that text to be more vivid, specific, and production-ready — keep the user's original intent and any facts they included (price, materials, etc.), but sharpen the language, add concrete sensory/visual detail appropriate to the chosen style, and keep it concise (1-3 sentences).
Respond with ONLY the rewritten text. No preamble, no quotes, no markdown, no labels.`;

  const userPrompt = `${contextLines}\n\nCurrent ${FIELD_LABELS[field]}:\n"""${text.trim()}"""\n\nRewrite it now.`;

  const nvidia = new NvidiaProvider(apiKeys.nvidia.api_key);
  let data;
  try {
    data = await nvidia.chatCompletion(
      [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      { model, temperature: 0.8, max_tokens: 300 }
    );
  } catch (err) {
    throw new Error(`NVIDIA API error: ${err.message}`);
  }

  let enhanced = data.choices?.[0]?.message?.content?.trim() || '';
  // Strip accidental wrapping quotes the model sometimes adds.
  enhanced = enhanced.replace(/^["'""](.*?)["'"]$/s, '$1').trim();

  return {
    field,
    enhanced,
    model,
    usage: data.usage,
  };
}

// ──────────────────────────────────────────────
// "Rewrite Prompt" mode — backed by prompt_rewrite_templates (see
// migrations/add_prompt_rewrite_templates_table.sql). Rows are inserted
// manually. Flow: user picks Category -> Prompt (both loaded from this
// table), fills in brand/tagline/items/address/contact, and an NVIDIA
// model rewrites the selected reference prompt around those details —
// unlike Step 4's generate_full_prompt, this DOES call an AI model, since
// the reference prompts are free-form prose (no fixed {placeholder}
// tokens) and the item count varies, so the beat/scene structure and any
// timing math has to be re-flowed rather than substituted.
// ──────────────────────────────────────────────

// GET /api/modules/prompt-builder/rewrite-categories
async function listRewriteCategories() {
  const result = await pool.query(
    `SELECT DISTINCT category FROM prompt_rewrite_templates WHERE is_active = true ORDER BY category ASC`
  );
  return result.rows.map(r => r.category);
}

// GET /api/modules/prompt-builder/rewrite-templates?category=...
async function listRewriteTemplates(category) {
  if (!category || !category.trim()) {
    throw new Error('category is required');
  }
  const result = await pool.query(
    `SELECT id, name, duration, prompt
     FROM prompt_rewrite_templates
     WHERE category = $1 AND is_active = true
     ORDER BY name ASC`,
    [category.trim()]
  );
  return result.rows;
}

async function getRewriteTemplateById(id) {
  const result = await pool.query(
    `SELECT id, name, category, duration, prompt
     FROM prompt_rewrite_templates
     WHERE id = $1 AND is_active = true`,
    [id]
  );
  return result.rows[0] || null;
}

// action: 'rewrite_prompt' (dispatched from enhanceField above)
// body: {
//   templateId: string,          // id of a prompt_rewrite_templates row
//   brandName: string,           // required
//   tagline: string,             // optional
//   items: [{ name, price }],    // 1-5, at least one named item required
//   address: string,             // required
//   contact: string,             // required
//   model                        // optional override
// }
//
// Note: the reference prompt text itself is always re-fetched from the DB
// by templateId rather than trusted from the request body, so the model
// only ever rewrites vetted template content, never arbitrary client text.
async function rewritePrompt(requestBody, apiKeys) {
  const {
    templateId,
    brandName = '',
    tagline = '',
    items = [],
    address = '',
    contact = '',
    model: requestedModel,
  } = requestBody;

  if (!templateId) {
    throw new Error('Pick a prompt template first');
  }
  if (!brandName.trim()) {
    throw new Error('Brand name is required');
  }
  if (!address.trim()) {
    throw new Error('Address is required');
  }
  if (!contact.trim()) {
    throw new Error('Contact is required');
  }
  const cleanItems = (items || [])
    .filter(i => i && i.name && i.name.trim())
    .slice(0, 5)
    .map(i => ({ name: i.name.trim(), price: (i.price || '').trim() }));
  if (!cleanItems.length) {
    throw new Error('Add at least one item');
  }
  if (!apiKeys.nvidia?.api_key) {
    throw new Error('NVIDIA API key not configured. Add it in Profile > API Keys.');
  }

  const template = await getRewriteTemplateById(templateId);
  if (!template) {
    throw new Error('Selected template was not found or is no longer active.');
  }

  const model = NVIDIA_MODELS.includes(requestedModel) ? requestedModel : DEFAULT_MODEL;

  const itemsList = cleanItems
    .map((it, i) => `${i + 1}. ${it.name}${it.price ? ` — ${it.price}` : ''}`)
    .join('\n');

  const systemPrompt = `You are an expert AI video-prompt copywriter.
You will be given a REFERENCE PROMPT — a full, structured AI-video-generation prompt written for a different brand — and REPLACEMENT DETAILS for a new brand.

Regenerate the prompt by replacing the brand name, address, contact and the items as given here, while preserving the reference prompt's structure, format, and technical directives (aspect ratio, duration, style, lighting notes).

Rules:
- Replace every brand name, tagline, address, and contact/phone mention with the new brand's details.
- The reference prompt has its own number of item "beats"/scenes. The new brand has a different number of items — add, remove, or merge beat blocks so there is exactly one beat per new item, in the order given, renumbering beats and recalculating any timing math (total duration, per-beat seconds, timestamps) so it stays internally consistent for the new item count.
- Keep all non-brand-specific creative direction unchanged: camera language, lighting style, transitions, aesthetic, aspect ratio, overall format.
- If no tagline is provided, omit the tagline line rather than inventing one.
- Output ONLY the complete rewritten prompt as plain text. No preamble, no explanation, no markdown code fences, no labels.`;

  const userPrompt = `REFERENCE PROMPT:
"""
${template.prompt}
"""

REPLACEMENT DETAILS:
Brand Name: ${brandName.trim()}
Tagline: ${tagline.trim() || '(none provided — omit tagline line)'}
Address: ${address.trim()}
Contact: ${contact.trim()}
Items (use exactly these, one beat per item, in this order):
${itemsList}

Rewrite the prompt now.`;

  const nvidia = new NvidiaProvider(apiKeys.nvidia.api_key);
  let data;
  try {
    data = await nvidia.chatCompletion(
      [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      { model, temperature: 0.7, max_tokens: 2000 }
    );
  } catch (err) {
    throw new Error(`NVIDIA API error: ${err.message}`);
  }

  let rewritten = data.choices?.[0]?.message?.content?.trim() || '';
  // Strip accidental markdown code fences the model sometimes adds.
  rewritten = rewritten.replace(/^```[a-z]*\n?/i, '').replace(/```$/, '').trim();

  return {
    prompt: rewritten,
    templateId: template.id,
    templateName: template.name,
    model,
    usage: data.usage,
  };
}

module.exports = {
  listStyles,
  enhanceField,
  generateFullPrompt,
  getModelCatalog,
  listRewriteCategories,
  listRewriteTemplates,
  rewritePrompt,
  STYLE_OPTIONS,
  NVIDIA_MODELS,
};